USE life_point;

INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('1. Happiness is my  birthright. I embrace happiness as my set point state of being.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('2. it, I feel joy and contentment in this moment right now.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('3. I awake up in the  morning feeling happy and enthusiastic about my life.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('4. I can tap into a wellspring of inner happiness anytime I  wish.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('5. By allowing myself to be  happy, I inspire others to be happy as well.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('6. I have fun with all of my endeavors, even the most mundane.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('7. I look at the  world around me and can’t help but smile and feel joy.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('8. I find joy and pleasure in the most simple things in life.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('9. I have an active sense of humor and love to share laughter with other people.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('10. My heart is overflowing with joy.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('11. I rest in happiness when I go to sleep, knowing all is well in my world.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('12. My partner and I share a deep and powerful love for each other.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('13. I respect and admire my partner and see the best in them.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('14. I love my partner exactly how they are and enjoy their unique qualities.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('15. My partner and I share emotional intimacy daily through talking and touch.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('16. I have healthy boundaries with my partner.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('17. My partner and I have fun together and find new ways to enjoy our time together.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('18. My partner and I communicate openly and resolve conflict peacefully and respectfully.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('19. I am able to be myself fully and completely authentic in my love relationship.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('20. I communicate my desires and needs clearly and confidently with my partner.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('21. I want the best for my partner and easily go out of my way to support them.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('22. I expect to be successful in all of my endeavors. Success is my natural state.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('23. I easily find solutions to challenges and roadblocks and move past them quickly.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('24. Mistakes and setbacks are stepping stones to my success because I learn from them.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('25. Every day in every way, I am becoming more and more successful.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('26. I feel successful with my life right now, even as I work toward future success.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('27. I know exactly what I need to do to achieve success.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('28. I see fear as the fuel for my success and take bold action in spite of fear.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('29. I feel powerful, capable, confident, energetic, and on top of the world.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('30. I have an intention for success and know it is a reality awaiting my arrival.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('31. I have now reached my goal of _______ and feel the excitement of my achievement.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('32. Today I am successful. Tomorrow I will be successful. Every day I am successful.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('33. When I breath, I inhale confidence and exhale timidity.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('34. I love meeting strangers and approach them with boldness and enthusiasm.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('35. I live in the present and am confident of the future.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('36. My personality exudes confidence. I am bold and outgoing.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('37. I am self-reliant, creative and persistent in whatever I do.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('38. I am energetic and enthusiastic. Confidence is my second nature.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('39. I always attract only the best of circumstances and the best positive people in my life.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('40. I am a problem solver. I focus on solutions and always find the best solution.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('41. I love change and easily adjust myself to new situations.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('42. I am well groomed, healthy and full of confidence. My outer self is matched by my inner well being.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('43. Self confidence is what I thrive on. Nothing is impossible and life is great.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('45. I always see only the good in others. I attract only positive confident people.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('46. I approve of myself and love myself deeply and completely.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('47. I am unique. I feel good about being alive and being me.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('48. I trust myself and know my inner wisdom is my best guide.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('49. I have integrity. I am totally reliable. I do what I say.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('50. I act from a place of personal security.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('51. I fully accept myself and know that I am worthy of great things in life.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('52. I choose to be proud of myself.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('53. I find deep inner peace within myself as I am.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('54. I fill my mind with positive and nourishing thoughts.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('55. My confidence, self esteem, and inner wisdom are increasing with each day.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('56. My immune system is very strong and can deal with any kind of bacteria, germs and viruses.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('57. Every cell in my body vibrates with energy and health.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('58. I am completely pain free, and my body is full of energy.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('59. I nourish my body with healthy food.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('60. All of my body systems are functioning perfectly..', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('61. My body is healing, and I feel better and better every day.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('62. I enjoy exercising my body and strengthening my muscles.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('63. With every breath out, I release stress in my body.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('64. I send love and healing to every organ of my body.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('65. I breathe deeply, exercise regularly and feed only good nutritious food to my body.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('66. I pay attention and listen to what my body needs for health and vitality.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('67. I sleep soundly and peacefully, and awaken feeling rested and energetic.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('68. I am surrounded by people who encourage and support healthy choices.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('69. My world is a peaceful, loving, and joy-filled place to live.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('70. I sow the seeds of peace wherever I go.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('71. I surround myself with peaceful people.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('72. My work environment is calm and peaceful.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('73. I breath in peace, I breath out chaos and disorder.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('74. My home is a peaceful sanctuary where I feel safe and happy.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('75. In all that I say and do, I choose peace.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('76. I release past anger and hurts and fill myself with serenity and peaceful thoughts.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('77. Peace descends all around me now and always.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('78. I send peace from myself into the world.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('79. I respond peacefully in all situations.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('80. I am grounded in the experience of the present moment.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('81. I am focus and engaged in the task at hand.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('82. All is well right now.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('83. I am grateful for this moment and find joy in it.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('84. I gently and easily return to the present moment.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('85. I observe my thoughts and actions without judging them.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('86. I am fully present in all of my relationships.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('87. Life is happening in this moment.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('88. I accept and embrace all experiences, even unpleasant ones.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('89. I observe my emotions without getting attached to them.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('90. I meditate easily without resistance or anxiety.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('91. I release the past and live fully in the present moment.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('92. Calmness washes over me with every deep breath I take.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('93. Every day I am more and more at ease.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('94. Being calm and relaxed energizes my whole being.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('95. All the muscles in my body are releasing and relaxing.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('96. All negativity and stress are evaporating from my body and my mind.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('97. I breath in relaxation. I breath out stress.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('98. Even when there is chaos around me, I remain calm and centered.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('99. I transcend stress of any kind. I live in peace.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('100. I am free of anxiety, and a calm inner peace fills my mind and body.', curDate(), curDate());
INSERT INTO affirmations (quote, createdAt, updatedAt) VALUES ('101. All is well in my world. I am calm, happy, and content.', curDate(), curDate());