INSERT INTO affirmations (quote) VALUES ('1. Happiness is my  birthright. I embrace happiness as my set point state of being.');
INSERT INTO affirmations (quote) VALUES ('2. it, I feel joy and contentment in this moment right now.');
INSERT INTO affirmations (quote) VALUES ('3. I awake up in the  morning feeling happy and enthusiastic about my life.');
INSERT INTO affirmations (quote) VALUES ('4. I can tap into a wellspring of inner happiness anytime I  wish.');
INSERT INTO affirmations (quote) VALUES ('5. By allowing myself to be  happy, I inspire others to be happy as well.');
INSERT INTO affirmations (quote) VALUES ('6. I have fun with all of my endeavors, even the most mundane.');
INSERT INTO affirmations (quote) VALUES ('7. I look at the  world around me and can’t help but smile and feel joy.');
INSERT INTO affirmations (quote) VALUES ('8. I find joy and pleasure in the most simple things in life.');
INSERT INTO affirmations (quote) VALUES ('9. I have an active sense of humor and love to share laughter with other people.');
INSERT INTO affirmations (quote) VALUES ('10. My heart is overflowing with joy.');
INSERT INTO affirmations (quote) VALUES ('11. I rest in happiness when I go to sleep, knowing all is well in my world.');
INSERT INTO affirmations (quote) VALUES ('12. My partner and I share a deep and powerful love for each other.');
INSERT INTO affirmations (quote) VALUES ('13. I respect and admire my partner and see the best in them.');
INSERT INTO affirmations (quote) VALUES ('14. I love my partner exactly how they are and enjoy their unique qualities.');
INSERT INTO affirmations (quote) VALUES ('15. My partner and I share emotional intimacy daily through talking and touch.');
INSERT INTO affirmations (quote) VALUES ('16. I have healthy boundaries with my partner.');
INSERT INTO affirmations (quote) VALUES ('17. My partner and I have fun together and find new ways to enjoy our time together.');
INSERT INTO affirmations (quote) VALUES ('18. My partner and I communicate openly and resolve conflict peacefully and respectfully.');
INSERT INTO affirmations (quote) VALUES ('19. I am able to be myself fully and completely authentic in my love relationship.');
INSERT INTO affirmations (quote) VALUES ('20. I communicate my desires and needs clearly and confidently with my partner.');
INSERT INTO affirmations (quote) VALUES ('21. I want the best for my partner and easily go out of my way to support them.');
INSERT INTO affirmations (quote) VALUES ('22. I expect to be successful in all of my endeavors. Success is my natural state.');
INSERT INTO affirmations (quote) VALUES ('23. I easily find solutions to challenges and roadblocks and move past them quickly.');
INSERT INTO affirmations (quote) VALUES ('24. Mistakes and setbacks are stepping stones to my success because I learn from them.');
INSERT INTO affirmations (quote) VALUES ('25. Every day in every way, I am becoming more and more successful.');
INSERT INTO affirmations (quote) VALUES ('26. I feel successful with my life right now, even as I work toward future success.');
INSERT INTO affirmations (quote) VALUES ('27. I know exactly what I need to do to achieve success.');
INSERT INTO affirmations (quote) VALUES ('28. I see fear as the fuel for my success and take bold action in spite of fear.');
INSERT INTO affirmations (quote) VALUES ('29. I feel powerful, capable, confident, energetic, and on top of the world.');
INSERT INTO affirmations (quote) VALUES ('30. I have an intention for success and know it is a reality awaiting my arrival.');
INSERT INTO affirmations (quote) VALUES ('31. I have now reached my goal of _______ and feel the excitement of my achievement.');
INSERT INTO affirmations (quote) VALUES ('32. Today I am successful. Tomorrow I will be successful. Every day I am successful.');
INSERT INTO affirmations (quote) VALUES ('33. When I breath, I inhale confidence and exhale timidity.');
INSERT INTO affirmations (quote) VALUES ('34. I love meeting strangers and approach them with boldness and enthusiasm.');
INSERT INTO affirmations (quote) VALUES ('35. I live in the present and am confident of the future.');
INSERT INTO affirmations (quote) VALUES ('36. My personality exudes confidence. I am bold and outgoing.');
INSERT INTO affirmations (quote) VALUES ('37. I am self-reliant, creative and persistent in whatever I do.');
INSERT INTO affirmations (quote) VALUES ('38. I am energetic and enthusiastic. Confidence is my second nature.');
INSERT INTO affirmations (quote) VALUES ('39. I always attract only the best of circumstances and the best positive people in my life.');
INSERT INTO affirmations (quote) VALUES ('40. I am a problem solver. I focus on solutions and always find the best solution.');
INSERT INTO affirmations (quote) VALUES ('41. I love change and easily adjust myself to new situations.');
INSERT INTO affirmations (quote) VALUES ('42. I am well groomed, healthy and full of confidence. My outer self is matched by my inner well being.');
INSERT INTO affirmations (quote) VALUES ('43. Self confidence is what I thrive on. Nothing is impossible and life is great.');
INSERT INTO affirmations (quote) VALUES ('45. I always see only the good in others. I attract only positive confident people.');
INSERT INTO affirmations (quote) VALUES ('46. I approve of myself and love myself deeply and completely.');
INSERT INTO affirmations (quote) VALUES ('47. I am unique. I feel good about being alive and being me.');
INSERT INTO affirmations (quote) VALUES ('48. I trust myself and know my inner wisdom is my best guide.');
INSERT INTO affirmations (quote) VALUES ('49. I have integrity. I am totally reliable. I do what I say.');
INSERT INTO affirmations (quote) VALUES ('50. I act from a place of personal security.');
INSERT INTO affirmations (quote) VALUES ('51. I fully accept myself and know that I am worthy of great things in life.');
INSERT INTO affirmations (quote) VALUES ('52. I choose to be proud of myself.');
INSERT INTO affirmations (quote) VALUES ('53. I find deep inner peace within myself as I am.');
INSERT INTO affirmations (quote) VALUES ('54. I fill my mind with positive and nourishing thoughts.');
INSERT INTO affirmations (quote) VALUES ('55. My confidence, self esteem, and inner wisdom are increasing with each day.');
INSERT INTO affirmations (quote) VALUES ('56. My immune system is very strong and can deal with any kind of bacteria, germs and viruses.');
INSERT INTO affirmations (quote) VALUES ('57. Every cell in my body vibrates with energy and health.');
INSERT INTO affirmations (quote) VALUES ('58. I am completely pain free, and my body is full of energy.');
INSERT INTO affirmations (quote) VALUES ('59. I nourish my body with healthy food.');
INSERT INTO affirmations (quote) VALUES ('60. All of my body systems are functioning perfectly..');
INSERT INTO affirmations (quote) VALUES ('61. My body is healing, and I feel better and better every day.');
INSERT INTO affirmations (quote) VALUES ('62. I enjoy exercising my body and strengthening my muscles.');
INSERT INTO affirmations (quote) VALUES ('63. With every breath out, I release stress in my body.');
INSERT INTO affirmations (quote) VALUES ('64. I send love and healing to every organ of my body.');
INSERT INTO affirmations (quote) VALUES ('65. I breathe deeply, exercise regularly and feed only good nutritious food to my body.');
INSERT INTO affirmations (quote) VALUES ('66. I pay attention and listen to what my body needs for health and vitality.');
INSERT INTO affirmations (quote) VALUES ('67. I sleep soundly and peacefully, and awaken feeling rested and energetic.');
INSERT INTO affirmations (quote) VALUES ('68. I am surrounded by people who encourage and support healthy choices.');
INSERT INTO affirmations (quote) VALUES ('69. My world is a peaceful, loving, and joy-filled place to live.');
INSERT INTO affirmations (quote) VALUES ('70. I sow the seeds of peace wherever I go.');
INSERT INTO affirmations (quote) VALUES ('71. I surround myself with peaceful people.');
INSERT INTO affirmations (quote) VALUES ('72. My work environment is calm and peaceful.');
INSERT INTO affirmations (quote) VALUES ('73. I breath in peace, I breath out chaos and disorder.');
INSERT INTO affirmations (quote) VALUES ('74. My home is a peaceful sanctuary where I feel safe and happy.');
INSERT INTO affirmations (quote) VALUES ('75. In all that I say and do, I choose peace.');
INSERT INTO affirmations (quote) VALUES ('76. I release past anger and hurts and fill myself with serenity and peaceful thoughts.');
INSERT INTO affirmations (quote) VALUES ('77. Peace descends all around me now and always.');
INSERT INTO affirmations (quote) VALUES ('78. I send peace from myself into the world.');
INSERT INTO affirmations (quote) VALUES ('79. I respond peacefully in all situations.');
INSERT INTO affirmations (quote) VALUES ('80. I am grounded in the experience of the present moment.');
INSERT INTO affirmations (quote) VALUES ('81. I am focus and engaged in the task at hand.');
INSERT INTO affirmations (quote) VALUES ('82. All is well right now.');
INSERT INTO affirmations (quote) VALUES ('83. I am grateful for this moment and find joy in it.');
INSERT INTO affirmations (quote) VALUES ('84. I gently and easily return to the present moment.');
INSERT INTO affirmations (quote) VALUES ('85. I observe my thoughts and actions without judging them.');
INSERT INTO affirmations (quote) VALUES ('86. I am fully present in all of my relationships.');
INSERT INTO affirmations (quote) VALUES ('87. Life is happening in this moment.');
INSERT INTO affirmations (quote) VALUES ('88. I accept and embrace all experiences, even unpleasant ones.');
INSERT INTO affirmations (quote) VALUES ('89. I observe my emotions without getting attached to them.');
INSERT INTO affirmations (quote) VALUES ('90. I meditate easily without resistance or anxiety.');
INSERT INTO affirmations (quote) VALUES ('91. I release the past and live fully in the present moment.');
INSERT INTO affirmations (quote) VALUES ('92. Calmness washes over me with every deep breath I take.');
INSERT INTO affirmations (quote) VALUES ('93. Every day I am more and more at ease.');
INSERT INTO affirmations (quote) VALUES ('94. Being calm and relaxed energizes my whole being.');
INSERT INTO affirmations (quote) VALUES ('95. All the muscles in my body are releasing and relaxing.');
INSERT INTO affirmations (quote) VALUES ('96. All negativity and stress are evaporating from my body and my mind.');
INSERT INTO affirmations (quote) VALUES ('97. I breath in relaxation. I breath out stress.');
INSERT INTO affirmations (quote) VALUES ('98. Even when there is chaos around me, I remain calm and centered.');
INSERT INTO affirmations (quote) VALUES ('99. I transcend stress of any kind. I live in peace.');
INSERT INTO affirmations (quote) VALUES ('100. I am free of anxiety, and a calm inner peace fills my mind and body.');
INSERT INTO affirmations (quote) VALUES ('101. All is well in my world. I am calm, happy, and content.')